name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8.16.1, 10.16.3, 12.11.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: INSTALL AND BUILD
      run: |
        npm install
        npm run dist --if-present
      env:
        CI: true
